FROM openjdk:17 
EXPOSE 8080 
ADD target/ust_busbooking_Apigateway-0.0.1-SNAPSHOT.jar ust_busbooking_Apigateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","ust_busbooking_Apigateway-0.0.1-SNAPSHOT.jar"]